apiVersion: v1
kind: Service
metadata:
  name: admin-{{ template "ocelot.fullname" . }}
  labels:
    app: admin-{{ template "ocelot.name" . }}
    chart: {{ template "ocelot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: 10000
      nodePort: {{.Values.admin.service.nodePort}}
      protocol: TCP
      name: grpc
  selector:
    app: admin-{{ template "ocelot.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: admin-{{ template "ocelot.fullname" . }}-internal
spec:
  ports:
  - name: grpc
    port: 10000
    protocol: TCP
    targetPort: 10000
#  - name: http
#    port: 11000
#    protocol: TCP
#    targetPort: 11000
  selector:
    app: admin-{{ template "ocelot.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-admin
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 11000
      targetPort: 11000
      protocol: TCP
      name: http
  selector:
    app: admin-{{ template "ocelot.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: hookhandler-{{ template "ocelot.fullname" . }}
  labels:
    app: hookhandler-{{ template "ocelot.name" . }}
    chart: {{ template "ocelot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.hookhandler.service.type }}
  ports:
    - port: {{ .Values.hookhandler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hookhandler-{{ template "ocelot.name" . }}
    release: {{ .Release.Name }}
