version: "3.3"
services:
  nsqlookupd:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
    ports:
      - 4160:4160
      - 4161:4161
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nsqd:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address localhost
      -lookupd-tcp-address nsqlookupd:4160
    ports:
      - 4150:4150
      - 4151:4151
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"