[package]
name = "orb"
version = "0.1.0"
authors = ["T.J. Telan <tjtelan@level11.com>"]
edition = "2018"
default-run = "orb"

[dependencies]
structopt = "0.3"
clap = "2.33"
tonic = { version = "0.1.0-alpha.6", features = [ "rustls"] }
tokio = "=0.2.0-alpha.6"
env_logger = "0.7"
orbital_headers = { path = "../../models/orbital_headers" }
orbital_cli_subcommand = { path = "src/subcommand" }
orbital_services = { path = "../../services"}
